import type { KendoTIType, TypeCode } from './types'

export const kendoTypes: Record<TypeCode, KendoTIType> = {
  AJRG: {
    code: 'AJRG',
    nickname: 'KING',
    name: '道場王者',
    slogan: '你是那種打一場就會有人默默截圖上傳的劍士',
    description:
      '你身上有種讓人心浮氣躁的穩定感。攻得主動、打得規範、想得冷靜、守得扎實。別人試合靠運氣,你試合靠早就寫好的腳本。所謂道場王者不是最猛,是最不出錯。你的動作乾淨到可以當教學影片,你的判斷精準到讓對手懷疑自己練的是不是同一門劍道。你不追求花俏,追求該打的有打、不該打的絕不冒險。師範喜歡你,因為你是活體示範;同門怕你,因為你是那面讓人看清自己不足的鏡子。你最大的秘密是你其實很愛贏,只是不屑用髒招。',
    strengths: ['動作完成度高,試合失誤率低', '壓迫感穩定,對手總是先慌', '基本功紮實,段審必過'],
    weaknesses: ['過度規範,缺乏出奇制勝的爆發', '對自己太嚴格,連帶對新人沒耐心', '太像標準答案,讓人提不起勁學你'],
    peerReview:
      '新人看到你第一反應是「天啊這人好帥」,一個月後變成「這人是機器人吧」。你不會主動社交,但所有人私下都想跟你學。你的存在讓道場氣氛多了 10% 的認真度,少了 30% 的放鬆感。',
    prescription: '你最大的敵人不是對手,是你對完美的執著。偶爾放掉一兩個出頭小手,偶爾打一記不太規範但很爽的胴。你該練的不是更強,是允許自己不完美。',
    nemesis: { code: 'AKSH', reason: '他打不贏你,但會用亂七八糟的氣合聲和不照腳本的動作把你心態搞爛' },
    partner: { code: 'AKRG', reason: '你主攻他主算,一動一靜組隊幾乎無解' },
    historicalFigure: '宮本武藏(二天一流完成期,非晚年五輪書版)',
    mangaCharacter: '緋村劍心 · 追憶篇',
    modernExample: '全日本選手權決勝圈裡「怎麼打都不犯錯」的教士級劍士',
    injuries: ['膝蓋(過度追求規範踏步導致髕骨壓力)', '右肘(追求打擊完成度的慢性勞損)'],
    prevention: '每週至少 1 次柔軟度訓練、1 次不穿防具的自由素振釋放肌肉',
    evolution: [
      { stage: '初段', state: '被稱讚動作漂亮但被嫌沒氣勢' },
      { stage: '三段', state: '開始有壓迫感,試合勝率顯著拉高,有人開始想跟你對練' },
      { stage: '五段', state: '變成那個大家都不想跟你比試合的人' },
      { stage: '七段後', state: '可能開道場成為別人的 SIFU,或轉研究型變教練而非選手' },
    ],
    loveMatch: { code: 'UJSG', reason: '你嚴他暖,道場 CP 模範生' },
    loveAvoid: { code: 'AJSH', reason: '他演戲你想靜,三天兩頭翻臉' },
    loveBonus: '跟你交往的人會學會怎麼摺劍道衣。這是好事也是壞事。',
    shareText: '我的 kendoTI:KING · 道場王者\n基本功像字帖,壓迫感像段審。\n試合靠腳本,練習當字寫。\n不是最受歡迎的,是最被默默尊敬的。',
    stats: { men: 8, kote: 7, do: 7, kiai: 7, maai: 9, zanshin: 9 },
    portrait: '/kendoti/personas/AJRG.png',
  },
  AJRH: {
    code: 'AJRH',
    nickname: 'BOSS',
    name: '試合大魔王',
    slogan: '練習 70 分,比賽 120 分。平時看不出來,上場嚇死你',
    description:
      '你平時稽古看起來很平凡,甚至有點懶散。但開幕鐘一響,整個人像換皮。攻得主動、技術到位、腦袋清楚、臨場變招狠。你最大的資產不是技術,是「會贏」這件事本身。你讀對手的方式像下棋,每一步都有三種預備反應。道場裡的人喜歡跟你聊天,但沒有人喜歡跟你比試合。你喜歡輸給自己的腳本,討厭輸給不照腳本打的人。',
    strengths: ['試合爆發力頂級', '讀局能力強,對手的第二手你已經在準備', '壓力愈大發揮愈好'],
    weaknesses: ['日常稽古容易偷懶', '輸給弱於自己的人心態會崩', '太靠臨場判斷,遇到怪咖會吃癟'],
    peerReview: '平常覺得你「還好」,直到試合看到你,才驚覺你藏了九成實力。道場裡有種傳說:「不要跟 BOSS 打試合,他平常只露了 1/10」。',
    prescription: '你該把試合的 120% 分一點到日常稽古。不是每個對手都值得你全力,但每次稽古都值得你認真 80%。',
    nemesis: { code: 'UKRH', reason: '你的腳本他都讀完了,只差 0.2 秒的反應差距,讓你讀不出他何時出手' },
    partner: { code: 'AJRG', reason: '他是教科書你是變招,組雙人超穩' },
    historicalFigure: '千葉周作(實戰與戰術極致並重的北辰一刀流宗師)',
    mangaCharacter: '黑崎一護(平時懶散戰時恐怖)',
    modernExample: '全國大會裡那種「資料上看不出很強但到決勝才恐怖」的怪物',
    injuries: ['左膝(試合爆發踏步的不對稱磨耗)', '腰椎(爆發變招的慢性壓迫)'],
    prevention: '試合前後各做一次完整的熱身/緩和,不要仗著年輕省略',
    evolution: [
      { stage: '初段', state: '大家覺得你只會打試合,平時還好' },
      { stage: '三段', state: '開始拿獎,但道場裡你還是那個「看起來沒在練的」' },
      { stage: '五段', state: '全國排名穩固,面子裡子一起收' },
      { stage: '七段後', state: '可能進入教練路,訓練國手或下一代 BOSS' },
    ],
    loveMatch: { code: 'UKSG', reason: '他穩如山你變如風,兩人互補到像早就該在一起' },
    loveAvoid: { code: 'AKSH', reason: '兩個人都想當主角,每天都在搶鏡頭' },
    loveBonus: '第一次約會你們就在討論試合策略。浪漫不浪漫看人。',
    shareText: '我的 kendoTI:BOSS · 試合大魔王\n平時看起來很懶,上場嚇死你。\n讀對手像下棋,變招狠如獵豹。\n你贏不了我的腳本,輸給我也別不甘。',
    stats: { men: 9, kote: 8, do: 7, kiai: 6, maai: 10, zanshin: 6 },
    portrait: '/kendoti/personas/AJRH.png',
  },
  AJSG: {
    code: 'AJSG',
    nickname: 'MEN!',
    name: '面打狂熱者',
    slogan: '三本打突只記得 MEN,但 MEN 打得又直又狠',
    description:
      '你對「打面」有種宗教般的執念。攻主動、動作規範、情緒熱血、基本功死守,你的每一場稽古就是把那支飛び込み面磨得更純。你不是不會其他技,是懶得用。對你來說劍道等於 MEN,其他都是點綴。你的氣合聲從走進道場開始就沒停過,你的面打命中率高到讓對手懷疑自己防具戴了沒。別人追求多樣,你追求的是「一招打穿所有人」。',
    strengths: ['面打命中率極高', '氣勢穩定,一整場維持爆發', '基本動作紮實到肌肉記憶'],
    weaknesses: ['技巧單一,遇到反擊型會吃大虧', '情緒一上來容易失控', '對小手胴無感,防守有破綻'],
    peerReview: '大家都知道你開場第一擊一定是面。但還是會被你打到。因為太準了。你進道場的聲音先到,人後到。',
    prescription: '偶爾打一次小手,你會發現世界很大。不要把劍道當 FPS 一招流,這樣會在五段卡關。',
    nemesis: { code: 'UKRH', reason: '他專等你的 MEN,你衝上去他 0.1 秒後返し胴就到了' },
    partner: { code: 'AJSH', reason: '兩個熱血仔一起喊,整個道場氣場拉滿' },
    historicalFigure: '上泉信綱(新陰流祖師,重視正面壓制)',
    mangaCharacter: '赤胴鈴之助(面打純粹派代表)',
    modernExample: '台灣大學生賽常見的「面打小霸王」類型',
    injuries: ['頸椎(飛び込み面頭部撞擊震盪累積)', '右肩'],
    prevention: '每月至少一次頸部拉伸和肩袖訓練,不要只顧打,要顧身體',
    evolution: [
      { stage: '初段', state: '全場都在防你的面,你還是打得進去' },
      { stage: '三段', state: '開始被逼練其他技,面打仍是主力' },
      { stage: '五段', state: '面打成為你的標誌,但你開始練小手返胴' },
      { stage: '七段後', state: '道場裡「那個面打超強的師範」' },
    ],
    loveMatch: { code: 'UJSG', reason: '你衝他穩,他包容你的執念還笑笑' },
    loveAvoid: { code: 'UKRG', reason: '他修行你在喊,宗教觀差太多' },
    loveBonus: '你在約會的時候會不自覺分析對方走路的節奏。是職業病。',
    shareText: '我的 kendoTI:MEN! · 面打狂熱者\n三本打突只記得 MEN。\n但 MEN 打得又直又狠。\n你防得了第一下,防不了第十下。',
    stats: { men: 10, kote: 3, do: 4, kiai: 8, maai: 6, zanshin: 6 },
    portrait: '/kendoti/personas/AJSG.png',
  },
  AJSH: {
    code: 'AJSH',
    nickname: 'SON',
    name: '熱血少年篇',
    slogan: '每次稽古都像最終話,氣合聲隔壁道場投訴',
    description:
      '你打劍道不是在打劍道,是在演「主角」。攻得主動、動作到位、情緒炸裂、臨場隨機應變,你的每一場試合都像週刊漫畫的決勝話。你的氣合聲像開大絕,你的表情像剛覺醒新能力。你打贏會抱隊友哭,打輸會蹲在場邊握拳。但別誤會,你技術是真的強,只是包裝得太華麗讓人分不清。道場裡每個人都有一瞬間被你的熱情感動,下一瞬間被你的音量嚇到。',
    strengths: ['氣合無敵,心理戰壓倒性', '現場反應快,擅長意外逆轉', '帶新人的熱情 100%'],
    weaknesses: ['消耗戰容易爆表', '情緒主導判斷,遇冷靜對手被抓節奏', '殘心常常忘記做'],
    peerReview: '道場氣氛靠你撐起來。沒有你的日子會很安靜。有你的日子會被投訴。但大家還是愛你,因為你真的很努力。',
    prescription: '學會把氣合收起來的那一秒,你會從少年升級成真正的劍士。熱血不是關掉,是學會開關。',
    nemesis: { code: 'AJRG', reason: '他的冷靜節奏把你的熱血全部吃掉,你越激動他越佔優' },
    partner: { code: 'AJSG', reason: '兩個面打狂加熱血少年,直接把道場打成演唱會' },
    historicalFigure: '坂本龍馬(熱血 + 行動派)',
    mangaCharacter: '竈門炭治郎(熱淚盈眶戰鬥型)',
    modernExample: '大學社團裡那個全場最吵最拼最被記得的學弟',
    injuries: ['喉嚨(長期大聲氣合聲帶勞損)', '大腿前側'],
    prevention: '氣合要發自丹田不要硬擠喉嚨,訓練後冰敷喉嚨',
    evolution: [
      { stage: '初段', state: '全場最吵,大家記得你的名字' },
      { stage: '三段', state: '開始學會什麼時候該安靜,但還是很吵' },
      { stage: '五段', state: '熱血不減,但氣合聲學會有節奏' },
      { stage: '七段後', state: '變成道場精神領袖,帶整代新人' },
    ],
    loveMatch: { code: 'UJSH', reason: '你熱他冷靜中帶暖,像火爐配毛毯' },
    loveAvoid: { code: 'AJRG', reason: '你想演戲他只想靜,兩週就分手' },
    loveBonus: '你們的交往公告會在道場公布欄貼一張心型照片。大家早就知道了。',
    shareText: '我的 kendoTI:SON · 熱血少年篇\n每次稽古都像最終話。\n氣合聲隔壁道場投訴。\n但你還是會笑著說下次再打。',
    stats: { men: 9, kote: 4, do: 5, kiai: 10, maai: 4, zanshin: 3 },
    portrait: '/kendoti/personas/AJSH.png',
  },
  AKRG: {
    code: 'AKRG',
    nickname: 'SIFU',
    name: '道場孔明',
    slogan: '打你之前已經預測你下三手',
    description:
      '你的劍道像下圍棋。攻得主動但不靠蠻力,靠間合、靠節奏、靠讀心。你的每一步都在計算對手下一步的概率,你的每一招都是為了引他進你設好的局。你不靠氣合壓人,靠沉默讓人不安。你打贏不是因為快,是因為對方根本還沒想好要打哪。道場裡的人喜歡觀察你,因為跟你對練一次等於上一堂戰術課。你最大的武器是你的眼睛,不是你的竹劍。',
    strengths: ['戰術讀局頂級,對手的下一步常被你預測', '間合控制精準', '段審面試超強(會講戰術理論)'],
    weaknesses: ['想太多,錯過果斷出手時機', '體力差,長試合會吃虧', '對本能型對手常常算不到'],
    peerReview: '大家覺得你很神秘。你不多話,但講出來的每一句都命中。道場傳言跟 SIFU 對練一次勝過練一週。',
    prescription: '偶爾不要想,讓身體先出手。你的腦袋是資產,也是枷鎖。',
    nemesis: { code: 'AKRH', reason: '他純靠本能反射,你的算計根本進不了他腦子' },
    partner: { code: 'AJRG', reason: '他執行你規劃,兩人組對就是隊伍大腦 + 雙腳' },
    historicalFigure: '塚原卜傳(間合與心理戰極致)',
    mangaCharacter: '奇犽 · 揍敵客(精密計算型)',
    modernExample: '全國賽教練席上看比賽看到笑的那位',
    injuries: ['頸椎(長期思考性頸肩緊繃)', '眼睛疲勞'],
    prevention: '每天 20 分鐘遠眺放鬆眼睛,別一直盯錄影',
    evolution: [
      { stage: '初段', state: '被嫌「想太多不敢打」' },
      { stage: '三段', state: '同門開始來問你戰術' },
      { stage: '五段', state: '開始被邀擔任助教,分析選手' },
      { stage: '七段後', state: '變成全國賽的御用分析教練' },
    ],
    loveMatch: { code: 'UKRG', reason: '兩個內省派,對話都很深,沒有廢話' },
    loveAvoid: { code: 'AJSH', reason: '一個想安靜一個要熱血,聊不到第三句' },
    loveBonus: '你會在交往第三個月畫出你對象的行為分析圖。對方可能會被嚇到。',
    shareText: '我的 kendoTI:SIFU · 道場孔明\n打你之前已經預測你下三手。\n我不靠快,我靠你根本還沒想好。\n跟我對練一次等於上一堂戰術課。',
    stats: { men: 6, kote: 9, do: 7, kiai: 5, maai: 10, zanshin: 9 },
    portrait: '/kendoti/personas/AKRG.png',
  },
  AKRH: {
    code: 'AKRH',
    nickname: 'HUNT',
    name: '野獸先鋒型',
    slogan: '不靠算,靠本能。你動他已經反射',
    description:
      '你打劍道像野獸狩獵。攻主動、靠直覺不靠理合、冷靜但兇、臨場變招狠。你讀對手不用腦子,用脊髓。對手起一點點破綻,你的身體已經動了,大腦還在後面追。你不解釋為什麼這樣打,就是這樣打。你對「招式」沒興趣,對「打中」有興趣。道場裡的人覺得你可怕不是因為你有多強,是因為你看起來完全不想「技術」這件事,卻次次都打中。',
    strengths: ['本能反應速度超人', '臨場隨機應變極強', '壓力下表現穩定,不會想太多'],
    weaknesses: ['姿勢長期不標準', '被理合派修理會被批爆', '段審書面分析題超低分'],
    peerReview: '大家不敢跟你對練太久,因為你每次都用不同的招打他們。你不是在對練,你是在狩獵。',
    prescription: '你該回頭練一下基本。本能是天賦,基本是壽命。沒基本的本能在五段後會斷崖。',
    nemesis: { code: 'UJRG', reason: '他用教科書修你,你的野路子在他面前每招都落空' },
    partner: { code: 'AKSH', reason: '兩個本能派,聯手沒招但對手打不到' },
    historicalFigure: '新免伊賀守(武藏之父,實戰暴力派)',
    mangaCharacter: '五条悟(超直覺戰鬥)',
    modernExample: '那種「姿勢不標準但沒人贏得了他」的野生道場強者',
    injuries: ['腳踝(野性反應的急轉傷)', '右手腕'],
    prevention: '每月做一次完整的基本動作檢視,別讓野性吃掉你的技',
    evolution: [
      { stage: '初段', state: '師範搖頭但打不過你' },
      { stage: '三段', state: '開始有人來研究你的「非基本打法」' },
      { stage: '五段', state: '如果你願意練基本,你就上神壇' },
      { stage: '七段後', state: '兩條路:野獸永遠是野獸,或晚期轉研究派' },
    ],
    loveMatch: { code: 'UJSH', reason: '你野他隨和,他不會想馴服你是關鍵' },
    loveAvoid: { code: 'UJRG', reason: '他會想改造你,你會爆氣' },
    loveBonus: '你在約會時會不自覺掃視房間安全出口。這是動物本能。',
    shareText: '我的 kendoTI:HUNT · 野獸先鋒型\n不靠算,靠本能。\n你動我已經反射。\n姿勢不標準,但你就是贏不了。',
    stats: { men: 8, kote: 8, do: 9, kiai: 7, maai: 5, zanshin: 4 },
    portrait: '/kendoti/personas/AKRH.png',
  },
  AKSG: {
    code: 'AKSG',
    nickname: 'KIAI',
    name: '氣合熔岩',
    slogan: '氣勢拉滿但技術普通,存在感比打擊還痛',
    description:
      '你打劍道不靠技術靠氣場。攻主動、靠直覺、情緒熱烈、基本功死守,你是道場的聲音擔當也是氣氛擔當。你的氣合聲讓整個道場抖一下,你的存在讓對手還沒出手就心理輸了。但別誤會,你不是只靠喊。你的基本扎實到能用氣合蓋過技巧差距。你的強不是「打得多漂亮」,是「對面還沒準備好就已經被你氣壓到不敢動」。',
    strengths: ['氣勢無敵,心理戰第一', '基本功死守不動搖', '稽古熱情帶動整個道場'],
    weaknesses: ['技術單調,變招少', '靠氣合撐,遇到冷靜對手會被打回原形', '體力消耗快'],
    peerReview: '道場的 BGM 就是你。沒有你的日子安靜到像墳場。有你的日子耳朵會累,但心會熱。',
    prescription: '你該學一兩招「不靠氣合」的技。有一天你會感冒,到那天你才知道基本功才是命根。',
    nemesis: { code: 'UKRG', reason: '他的殘心像水,你的氣合像火,他的穩定吃掉你的爆發' },
    partner: { code: 'AJSG', reason: '兩個熱情派一前一後,整個道場被炸裂' },
    historicalFigure: '武田信玄(氣場壓倒性的戰國武將)',
    mangaCharacter: '桜木花道(氣合 > 技術的代表)',
    modernExample: '道場創辦人的那種大叔,嗓門震到屋頂但教得超好',
    injuries: ['聲帶(長期氣合慢性勞損)', '膝蓋'],
    prevention: '每週一次不出聲稽古,練習用姿態代替氣合',
    evolution: [
      { stage: '初段', state: '「那個最吵的」稱號持有者' },
      { stage: '三段', state: '氣合成為個人標誌,對手先怕你' },
      { stage: '五段', state: '開始有人來學你的氣合方法' },
      { stage: '七段後', state: '道場老前輩,氣合一聲壓全場' },
    ],
    loveMatch: { code: 'UKSH', reason: '他佛系吸收你的火焰,你不會燒到他' },
    loveAvoid: { code: 'UKRG', reason: '他修行你在喊,頻率不同步' },
    loveBonus: '你在吵架時會忍不住發出氣合聲。對方可能會笑也可能會生氣。',
    shareText: '我的 kendoTI:KIAI · 氣合熔岩\n氣勢拉滿但技術普通。\n存在感比打擊還痛。\n沒有我的道場是墳場。',
    stats: { men: 7, kote: 3, do: 4, kiai: 10, maai: 5, zanshin: 6 },
    portrait: '/kendoti/personas/AKSG.png',
  },
  AKSH: {
    code: 'AKSH',
    nickname: 'BAKA',
    name: '燃燒中二病',
    slogan: '腦子還在熱身,身體已經開團。坂本龍馬投胎',
    description:
      '你打劍道是靠「燃」字。攻主動、靠直覺、情緒炸裂、臨場變招亂,你的每一場試合都像有背景音樂,每一次出手都像必殺技。你的動作不規範,你的判斷不冷靜,但你就是贏。為什麼?因為對手根本跟不上你的邏輯。你沒邏輯。你靠的是那個「幹就對了」的瞬間決斷。道場裡的人會笑你「阿呆」,但輸給你之後會偷偷練你的招。',
    strengths: ['爆發力無解', '無法預測的打法', '心理承受度超高,輸了還笑'],
    weaknesses: ['完全不練基本', '情緒失控會崩盤', '長試合體力跟不上'],
    peerReview: '你是道場的娛樂擔當,也是恐怖擔當。大家笑你,但沒人想跟你比試合。你就是那個會把整場變成動畫最終決戰的人。',
    prescription: '請你把「幹就對了」的能量,分 20% 給基本稽古。你有天賦,但天賦需要骨架。',
    nemesis: { code: 'AJRG', reason: '他用冷靜的教科書把你的中二病吃掉,你會越打越慌' },
    partner: { code: 'AKRH', reason: '兩個本能派聯手,沒有戰術但贏到底' },
    historicalFigure: '坂本龍馬',
    mangaCharacter: '魯夫',
    modernExample: '全國賽冷門爆冷的那種選手',
    injuries: ['肋骨(失控衝撞)', '手指'],
    prevention: '試合後強制 30 分鐘緩和,不要直接去跟人打',
    evolution: [
      { stage: '初段', state: '被罵阿呆但大家都愛' },
      { stage: '三段', state: '開始學基本,但還是最中二的那個' },
      { stage: '五段', state: '你已經是傳說,新人都聽過你當年的事蹟' },
      { stage: '七段後', state: '中二病不會好,你就是永遠的劍道少年' },
    ],
    loveMatch: { code: 'UJSH', reason: '他可以接住你所有的中二瞬間,不會笑你' },
    loveAvoid: { code: 'AJRG', reason: '他會邏輯分析你的中二,你會想分手' },
    loveBonus: '你在告白的時候會念出動漫台詞。對方會感動也會尷尬。',
    shareText: '我的 kendoTI:BAKA · 燃燒中二病\n腦子還在熱身,身體已經開團。\n沒邏輯,就贏。\n坂本龍馬投胎來打劍道。',
    stats: { men: 10, kote: 3, do: 4, kiai: 10, maai: 3, zanshin: 2 },
    portrait: '/kendoti/personas/AKSH.png',
  },
  UJRG: {
    code: 'UJRG',
    nickname: '2DAN',
    name: '萬年二段達人',
    slogan: '考了八次三段沒過,動作漂亮到評審懷疑人生',
    description:
      '你是那個「動作比五段還漂亮但過不了三段」的謎題。受動、術派、理性、守規,你的每一個動作都像教科書範例,但你就是不敢主動出手。段審時評審看你素振會點頭,看你試合時會搖頭。你的問題不是技術,是「太安全」。你怕錯,所以你什麼都不做。但你的基本功讓你在道場裡超受尊敬,新人都說「我想打得像他那樣」。你最大的秘密是你其實很想贏,只是不敢想。',
    strengths: ['基本功教科書等級', '動作美感頂級', '技術細節無可挑剔'],
    weaknesses: ['太安全,不敢打突破性的招', '段審面試心理壓力爆炸', '試合勝率偏低'],
    peerReview: '你的素振影片被傳到 LINE 群組當教材。但你試合紀錄表幾乎全是平手或一本敗。大家都希望你能勇敢一次。',
    prescription: '今天試合,你要主動出一次頭。錯了也沒關係。你的完美困住了你的進步。',
    nemesis: { code: 'AJRH', reason: '他會抓住你不敢出手的瞬間,把你殺得片甲不留' },
    partner: { code: 'UJRH', reason: '兩個受動派反而互相刺激,被逼著動起來' },
    historicalFigure: '柳生宗矩(技術純熟但性格謹慎)',
    mangaCharacter: '桐山零 · 三月的獅子前期(完美主義到自我懷疑)',
    modernExample: '考了三段八次都沒過但教一堆人過三段的那位道場大哥',
    injuries: ['心理壓力相關的腸胃症狀', '緊咬牙齒引起的顳顎關節'],
    prevention: '段審前不要看評審表,專注動作本身',
    evolution: [
      { stage: '初段', state: '大家都說你很快會三段' },
      { stage: '三段', state: '(考到第八次了)' },
      { stage: '五段', state: '如果你突破心理關卡,你會跳級到大家前面' },
      { stage: '七段後', state: '兩條路:心理過關成為大師,或永遠停留在技術純熟的二段' },
    ],
    loveMatch: { code: 'AJSH', reason: '他的熱血會逼你動起來,你的穩定會讓他不亂' },
    loveAvoid: { code: 'UJRH', reason: '兩個受動派交往會變成誰都不主動說我愛你' },
    loveBonus: '你會先想一百種表白方式,然後一個都不用。',
    shareText: '我的 kendoTI:2DAN · 萬年二段達人\n考了八次三段沒過。\n動作漂亮到評審懷疑人生。\n我不是不會,我只是不敢。',
    stats: { men: 5, kote: 8, do: 7, kiai: 4, maai: 9, zanshin: 9 },
    portrait: '/kendoti/personas/UJRG.png',
  },
  UJRH: {
    code: 'UJRH',
    nickname: 'ZZZZ',
    name: '裝死觀察者',
    slogan: '平時像關機,關鍵一瞬突然出頭小手',
    description:
      '你打劍道像冬眠的熊。受動、術派、理性、變通。95% 時間你在看、在讀、在評估。剩下 5% 時間你一口氣把對手打碎。道場裡的人以為你沒在練,因為你稽古都在「閒晃」。但其實你每一眼都在記對手的節奏。你不做無謂的動作,因為你的動作只為那一擊而存在。你的表情讓人以為你想睡,但你的出手快到沒人反應。',
    strengths: ['觀察力頂尖', '出頭小手命中率超高', '節能戰鬥,體力保留極佳'],
    weaknesses: ['日常稽古存在感很低', '主動戰鬥時會生鏽', '長試合會被逼動主動出手時失靈'],
    peerReview: '同門的你的評價兩極:一半覺得你很神,一半覺得你根本沒在練。直到你出手那一秒,所有人都閉嘴。',
    prescription: '偶爾主動出手一次,不要永遠等。你的節能不是節能,是怯場的美化。',
    nemesis: { code: 'AJRG', reason: '他不給你等的時間,主動壓制讓你沒機會觀察' },
    partner: { code: 'UKRH', reason: '兩個後發先至派,對方很難同時讀兩個人' },
    historicalFigure: '伊藤一刀齋(晚年沉潛觀察派)',
    mangaCharacter: '幽助(平常裝死戰時開大)',
    modernExample: '那種段審評審席上坐著看起來在打瞌睡但一看就看出你哪一招錯的老先生',
    injuries: ['下背(久站觀察)', '眼睛疲勞'],
    prevention: '觀察歸觀察,每場稽古至少主動出 10 次,不然身體會鈍化',
    evolution: [
      { stage: '初段', state: '被罵不積極,但段審前突然開掛' },
      { stage: '三段', state: '開始有人覺得你是高手,雖然看不出來' },
      { stage: '五段', state: '你的風格成為一種流派,叫「不動流」' },
      { stage: '七段後', state: '坐在那裡不動就是道場最高權威' },
    ],
    loveMatch: { code: 'AJSH', reason: '他會主動,你會適時回應,節奏剛剛好' },
    loveAvoid: { code: 'UJRG', reason: '兩個都在等對方先動,三年過去還在曖昧期' },
    loveBonus: '你會記住對方說過的每一句話,但不會主動提起。這是暖的也是累的。',
    shareText: '我的 kendoTI:ZZZZ · 裝死觀察者\n平時像關機。\n關鍵一瞬突然出頭小手。\n你看不出我在練,那是因為你沒在看。',
    stats: { men: 3, kote: 10, do: 7, kiai: 4, maai: 9, zanshin: 7 },
    portrait: '/kendoti/personas/UJRH.png',
  },
  UJSG: {
    code: 'UJSG',
    nickname: 'OYAJ',
    name: '道場老爸型',
    slogan: '不是最猛,是最會帶新人。道場情感基石',
    description:
      '你是道場的溫度。受動、術派、情感、守規。你打劍道不是為了贏,是為了「大家一起打劍道」這件事本身。你的技術不是最強,但你的存在讓道場不散。你會記得每個新人的名字,你會在別人氣餒時遞水給他,你會在師範罵人後私下安慰。你不是最搶眼的,但你是最重要的。沒有你,道場只是個場地;有你,道場才是個家。',
    strengths: ['情感支持力頂級', '帶新人耐心 100 分', '基本功紮實可靠'],
    weaknesses: ['自己的進步常被忽略', '試合狠不下心', '太在意他人情緒會內耗'],
    peerReview: '道場的空氣清淨機就是你。你在大家呼吸都比較順。新人哭過你陪過,老人累過你扶過。所有人都在心裡默默感謝你。',
    prescription: '你該偶爾自私一次。把今天的稽古時間留給自己,不要去關心新人。你也值得被照顧。',
    nemesis: { code: 'AKSH', reason: '他的混亂讓你心疼新人但又不能管,內心會糾結' },
    partner: { code: 'AJRG', reason: '你負責人心,他負責戰術,完美雙人組' },
    historicalFigure: '山岡鐵舟(武士道 + 仁義並重)',
    mangaCharacter: '劍心 · 維新後(溫柔但實力頂級)',
    modernExample: '每個地方道場都有的那位「X 叔」,大家最愛的前輩',
    injuries: ['背(長期幫新人調整姿勢的勞損)', '膝蓋'],
    prevention: '每月定期按摩,不要硬撐說自己還年輕',
    evolution: [
      { stage: '初段', state: '已經開始被叫「哥哥/姊姊」' },
      { stage: '三段', state: '正式成為新人引路人' },
      { stage: '五段', state: '大家叫你名字都會加尊稱' },
      { stage: '七段後', state: '你就是道場的靈魂,沒你這道場會崩' },
    ],
    loveMatch: { code: 'AJRG', reason: '你包容他嚴苛,他承擔你的情緒,互補剛剛好' },
    loveAvoid: { code: 'AKSH', reason: '他像小孩你像媽,累到你第二個月' },
    loveBonus: '你會在第一次約會時就開始想對方的父母生日。這是愛意也是職業病。',
    shareText: '我的 kendoTI:OYAJ · 道場老爸型\n不是最猛的,是最會帶新人的。\n道場的情感基石。\n沒有我的道場就只是個場地。',
    stats: { men: 6, kote: 7, do: 6, kiai: 7, maai: 8, zanshin: 9 },
    portrait: '/kendoti/personas/UJSG.png',
  },
  UJSH: {
    code: 'UJSH',
    nickname: 'OKLA',
    name: 'OK 啦台灣人',
    slogan: '不挑稽古對象,不怕亂流,打得出乎意料的準',
    description:
      '你打劍道像台灣人過日子:隨遇而安,但關鍵時刻總是穩。受動、術派、情感、變通。你不會強求「一定要這樣」,你會說 OK 啦看狀況。但別誤會,你的 OK 啦不是擺爛,是你真的適應力超強。道場的對手風格千變萬化,你每次都能找到打的方法。你沒有標誌性的招,因為你的標誌就是「跟你打永遠都不會太慘」。',
    strengths: ['適應力頂級', '全方位均衡沒有短板', '人緣好,對誰都能聊'],
    weaknesses: ['缺乏極致特色,記憶點不強', '重要比賽容易「OK 啦」下去', '段審會被嫌太鬆'],
    peerReview: '你是那種「誰都想跟你對練但沒人記得你的招是什麼」的人。道場裡公認的「可靠 OK 先生」。',
    prescription: '你該選一個技,練到變你的標誌。適應力是你的盾,但你需要一把劍。',
    nemesis: { code: 'AJSG', reason: '他的一招流讓你的全方位變模糊,你的 OK 打不到他的偏執' },
    partner: { code: 'AKSH', reason: '你 OK 他爆衝,你穩住場面讓他盡情發揮' },
    historicalFigure: '鄭成功(來台後的實用主義)',
    mangaCharacter: '卡卡西(對誰都能打,都打得不錯)',
    modernExample: '台灣大學生劍道隊那位「打哪都贏一點點」的隊長',
    injuries: ['沒什麼特別的,但偶爾會因為太放鬆吃小傷', '腰'],
    prevention: '偶爾認真一次,不要每次都 OK 啦,你的身體會感謝你',
    evolution: [
      { stage: '初段', state: '被說「很會交朋友但技術普通」' },
      { stage: '三段', state: '開始被注意到勝率超高' },
      { stage: '五段', state: '穩定高水準,但沒有代表作' },
      { stage: '七段後', state: '會變成那個「退休後大家都想找你吃飯」的前輩' },
    ],
    loveMatch: { code: 'AJSH', reason: '他演你接,他的熱血你能穩住,對你們來說都舒服' },
    loveAvoid: { code: 'UJRG', reason: '兩個受動派 OK 到底,永遠是好朋友進不了下一步' },
    loveBonus: '你在紀念日前三天會問對方「想吃什麼都 OK 啦」。對方會翻白眼也會笑。',
    shareText: '我的 kendoTI:OKLA · OK 啦台灣人\n不挑稽古對象,不怕亂流。\n打得出乎意料的準。\n跟我打,你不會太慘。',
    stats: { men: 6, kote: 7, do: 8, kiai: 6, maai: 7, zanshin: 7 },
    portrait: '/kendoti/personas/UJSH.png',
  },
  UKRG: {
    code: 'UKRG',
    nickname: 'NOZK',
    name: '殘心修行僧',
    slogan: '打完必殘心三秒,連素振都殘心。修的不是劍是自己',
    description:
      '你不是在練劍道,是在修行。受動、氣感、理性、守規。你打每一劍都像在寫書法。你的重點不是打中,是打完後那一秒的姿態。道場裡的人看你打覺得好像慢動作,但你每一下都到位。你不在乎勝負,你在乎「這一打我有沒有對得起自己」。大家看你會想到禪寺,不是競技場。你的強是一種靜態的強,對手打不碎你。',
    strengths: ['殘心頂級,每一招都完整', '心理穩定,不被外界影響', '段審的精神分數滿分'],
    weaknesses: ['試合節奏偏慢,容易被逼', '主動出手意願低', '現代賽制不利(秒數計時)'],
    peerReview: '你是道場的禪師。大家跟你打完都會覺得自己浮躁。新人覺得你高冷,老人覺得你境界高。',
    prescription: '修行很好,但偶爾要打得狠一點。劍道不是只有美,也有血性。',
    nemesis: { code: 'AJSH', reason: '他的熱血讓你的禪變成笑話,他根本不尊重你的節奏' },
    partner: { code: 'UKSG', reason: '兩個傳統派,默契像師兄弟' },
    historicalFigure: '宮本武藏 · 五輪書時期(晚年哲學化)',
    mangaCharacter: '比古清十郎',
    modernExample: '那位「大家不敢約對練但一起喝茶會很舒服」的老師範',
    injuries: ['膝蓋(長期跪坐/正座)', '腰椎'],
    prevention: '正座時間控制,每週做瑜珈或伸展',
    evolution: [
      { stage: '初段', state: '被嫌「動作太慢」' },
      { stage: '三段', state: '開始被說「有禪意」' },
      { stage: '五段', state: '評審會點頭微笑給你高分' },
      { stage: '七段後', state: '道場的精神象徵,大家遇到你會自動彎腰' },
    ],
    loveMatch: { code: 'AKRG', reason: '兩個思考派,心靈對話深度旁人聽不懂' },
    loveAvoid: { code: 'AJSH', reason: '他演你靜,他覺得你悶你覺得他吵' },
    loveBonus: '你會在對方說晚安後默默看著窗外三分鐘。那是你的殘心。',
    shareText: '我的 kendoTI:NOZK · 殘心修行僧\n打完必殘心三秒。\n連素振都殘心。\n修的不是劍,是自己。',
    stats: { men: 4, kote: 7, do: 6, kiai: 6, maai: 8, zanshin: 10 },
    portrait: '/kendoti/personas/UKRG.png',
  },
  UKRH: {
    code: 'UKRH',
    nickname: 'LAST',
    name: '後發先至仙人',
    slogan: '從不先動但總是最後得分。在等對手犯錯那 0.2 秒',
    description:
      '你是道場裡最可怕的存在。受動、氣感、理性、變通。你不出手,不是不會,是時機還沒到。你站在那裡像一堵牆,對手不得不動,一動就被你抓到。你的招在對手出手的瞬間才開始,在對手的招到你之前完成。你不是比他快,你是等在他必經的路上。大家跟你對練都有一個共同感受:「我到底是怎麼被打中的?」',
    strengths: ['後發先至頂尖', '小手返胴教科書等級', '心理戰讓對手先崩'],
    weaknesses: ['極少主動,被動防守賽會扣分', '連續被壓制會失去節奏', '帶新人太安靜不夠親切'],
    peerReview: '你是最讓人害怕的類型。因為你不動,對手不敢動;對手動了,你就贏了。是道場的無解題。',
    prescription: '偶爾主動出手一次,讓對手知道你也會先動。不然你會變成一個太預測的謎題。',
    nemesis: { code: 'AJRH', reason: '他的爆發速度讓你的後發都跟不上' },
    partner: { code: 'UJRH', reason: '兩個後發派配合,對手不知道該盯誰' },
    historicalFigure: '小野忠明(後發先至的一刀流傳人)',
    mangaCharacter: '雷獸(漂流武士)',
    modernExample: '日本警視廳劍道教士那種「站定了就是等你動」的大師',
    injuries: ['反應過度引起的慢性頸部緊繃', '腳踝'],
    prevention: '每週做一次反應速度訓練,避免身體失去動態感',
    evolution: [
      { stage: '初段', state: '被說「太被動」' },
      { stage: '三段', state: '開始被認可為「反擊流」' },
      { stage: '五段', state: '全國賽常見選手,後發先至代表' },
      { stage: '七段後', state: '進入教練路,訓練下一代反擊手' },
    ],
    loveMatch: { code: 'AKSH', reason: '他會先動,你會剛好接住,節奏互補' },
    loveAvoid: { code: 'UKRG', reason: '兩個受動派交往變成永遠沒人先開口' },
    loveBonus: '你會記得對方每一次生氣的原因,但不會主動問。你的後發先至是武器也是枷鎖。',
    shareText: '我的 kendoTI:LAST · 後發先至仙人\n從不先動但總是最後得分。\n在等對手犯錯那 0.2 秒。\n我不是慢,是你太早動了。',
    stats: { men: 3, kote: 10, do: 7, kiai: 5, maai: 10, zanshin: 8 },
    portrait: '/kendoti/personas/UKRH.png',
  },
  UKSG: {
    code: 'UKSG',
    nickname: 'BUDO',
    name: '武道傳承者',
    slogan: '講究禮儀 > 講究分數。打的是劍道不是打分遊戲',
    description:
      '你打劍道的出發點不是贏,是「傳承」。受動、氣感、情感、守規。你的禮儀是全道場模範,你的氣合是傳統氣合,你的每一個動作都像在做儀式。你對現代競技規則有點意見,你覺得劍道不應該只是分數。你會教新人先學禮再學打,你會在師範離開後留下來整理道場。你是那種「我打劍道是為了日本武道精神」的人,雖然你不是日本人。',
    strengths: ['禮儀氣場無敵', '傳統技法紮實', '能讓新人真正愛上劍道的文化'],
    weaknesses: ['現代賽制適應差', '對不尊重禮儀的對手特別討厭', '偶爾會說教'],
    peerReview: '你是道場的文化局長。沒有你,大家會忘記為什麼要鞠躬。有你,大家會記得劍道不只是打。',
    prescription: '現代賽制也是劍道的一部分,你該學會在傳統和現實之間切換。',
    nemesis: { code: 'AKSH', reason: '他完全不尊重你的禮儀,每次看到他你血壓都會升高' },
    partner: { code: 'UKRG', reason: '你們都敬畏武道,對話不用說太多' },
    historicalFigure: '柳生石舟齋(禮樂射御書數的武士道代表)',
    mangaCharacter: '緋村劍心(維新後的不殺之道)',
    modernExample: '台灣老派道場那位每次都要念一段武道精神的師範',
    injuries: ['腰(長期正座+鞠躬)', '膝蓋'],
    prevention: '正座時間控制,定期伸展',
    evolution: [
      { stage: '初段', state: '被當成「太嚴肅的那個」' },
      { stage: '三段', state: '開始被信任主持開練禮' },
      { stage: '五段', state: '代表道場出席重大儀式' },
      { stage: '七段後', state: '成為武道精神的代言人' },
    ],
    loveMatch: { code: 'AJRH', reason: '他負責現代,你負責傳統,兩個面向完整' },
    loveAvoid: { code: 'AKSH', reason: '他不尊重的方式會讓你每週都在生氣' },
    loveBonus: '你會在第一次牽手前先 45 度鞠躬。對方會笑,但會很感動。',
    shareText: '我的 kendoTI:BUDO · 武道傳承者\n講究禮儀 > 講究分數。\n打的是劍道,不是打分遊戲。\n沒有禮,你打得再好也不是劍道。',
    stats: { men: 5, kote: 6, do: 5, kiai: 9, maai: 7, zanshin: 10 },
    portrait: '/kendoti/personas/UKSG.png',
  },
  UKSH: {
    code: 'UKSH',
    nickname: 'FOMO',
    name: '佛系氣魄型',
    slogan: '氣場強但不爭。挑釁你微笑一下,然後把他打哭',
    description:
      '你是道場最反差的存在。受動、氣感、情感、變通。你看起來溫和到像僧人,但你的氣場讓對手不敢亂動。你不主動,但你的不主動本身就是壓力。你微笑、你鞠躬、你說「請多指教」,然後你用一招把對手打到懷疑人生。你從不生氣,因為你不需要。你的強不靠氣合聲,靠的是你的存在本身。',
    strengths: ['氣場內斂但壓倒性', '心理穩定到近乎禪定', '對手犯錯率在你面前極高'],
    weaknesses: ['容易被誤會沒在認真', '競技賽需要主動時會偏弱', '情緒壓抑,偶爾會內傷'],
    peerReview: '你是道場的謎。大家都跟你聊得愉快,但沒人敢跟你比試合。你的微笑比任何氣合聲都嚇人。',
    prescription: '你該偶爾把情緒表達出來,不要都壓在佛系面具下。氣魄可以溫和,但不該壓抑。',
    nemesis: { code: 'AKSG', reason: '他的氣合聲讓你的內斂被蓋過,你需要更強的存在感才能贏' },
    partner: { code: 'AKSG', reason: '他外顯你內斂,一熱一冷反而平衡' },
    historicalFigure: '一休宗純(禪僧 + 武藝)',
    mangaCharacter: '黑子哲也(存在感低但關鍵時刻爆炸)',
    modernExample: '那位全日本選手權決勝前永遠在笑的選手',
    injuries: ['情緒壓抑引起的胃部', '肩膀(長期沉穩姿勢)'],
    prevention: '定期找信任的人傾訴,不要把所有情緒都內化',
    evolution: [
      { stage: '初段', state: '被說「太溫和不夠殺」' },
      { stage: '三段', state: '開始被認可為「有內功」' },
      { stage: '五段', state: '變成道場的神秘存在' },
      { stage: '七段後', state: '成為那種「看著你笑你就會自己犯錯」的大師' },
    ],
    loveMatch: { code: 'AKSG', reason: '他的火你的水,你們互相照亮又不會燒到' },
    loveAvoid: { code: 'AKRH', reason: '他的野性你承受得了但會累死' },
    loveBonus: '你會在對方最崩潰的那一刻微笑並說「沒事」。那是最可怕也最安心的存在。',
    shareText: '我的 kendoTI:FOMO · 佛系氣魄型\n氣場強但不爭。\n挑釁我微笑一下,然後把你打哭。\n你打不贏我,因為我沒在跟你比。',
    stats: { men: 4, kote: 7, do: 6, kiai: 8, maai: 8, zanshin: 10 },
    portrait: '/kendoti/personas/UKSH.png',
  },
}

export function getType(code: TypeCode): KendoTIType {
  return kendoTypes[code]
}
