import type { Question } from './types'

export const questions: Question[] = [
  {
    id: 1,
    axis: 'strategy',
    genre: '中二病',
    prompt: '一上場,你腦中的第一句台詞是?',
    options: [
      { label: '「先下手為強」,腳已經在動了', score: { strategy: -2 } },
      { label: '「急什麼,他自己會犯錯」', score: { strategy: +2 } },
      { label: '嘴上說等,眼睛已經在掃破綻', score: { strategy: -1 } },
    ],
  },
  {
    id: 2,
    axis: 'strategy',
    genre: '現實殘酷',
    prompt: '對手段位比你高兩段,你會?',
    options: [
      { label: '反正打不贏,不如先狠狠打一下讓他記住我', score: { strategy: -2 } },
      { label: '安靜觀察他節奏,等他一個大意', score: { strategy: +2 } },
      { label: '禮貌試探,一被壓就開始裝傻應變', score: { strategy: +1 } },
    ],
  },
  {
    id: 3,
    axis: 'strategy',
    genre: '中二病',
    prompt: '你最愛打的技是?',
    options: [
      { label: '飛び込み面,直接撞上去', score: { strategy: -2 } },
      { label: '出頭小手 / 返し胴,等你動我得分', score: { strategy: +2 } },
      { label: '切返し正面壓進去,不花俏但踏實', score: { strategy: -1 } },
    ],
  },
  {
    id: 4,
    axis: 'strategy',
    genre: '人性弱點',
    prompt: '對方一直不出手,你會?',
    options: [
      { label: '我上,我不想站在這裡裝狠', score: { strategy: -2 } },
      { label: '完美,他越不動我越佔優勢', score: { strategy: +2 } },
      { label: '晃他兩下騙他先動,騙不到再上', score: { strategy: -1 } },
    ],
  },
  {
    id: 5,
    axis: 'strategy',
    genre: '道場黑歷史',
    prompt: '稽古開始鐘聲還沒響,你會?',
    options: [
      { label: '起跑線已經想好第一擊了', score: { strategy: -2 } },
      { label: '禮還沒行完別亂動,這樣不專業', score: { strategy: +2 } },
      { label: '裝鎮定但身體已經蓄力', score: { strategy: -1 } },
    ],
  },
  {
    id: 6,
    axis: 'strategy',
    genre: '現實殘酷',
    prompt: '連續被打中三次面,你會?',
    options: [
      { label: '這口氣不能吞,下一球我也要打進去', score: { strategy: -2 } },
      { label: '冷靜,他節奏太快,我換後發先至模式', score: { strategy: +2 } },
      { label: '表面冷靜,心裡想一上頭衝撞', score: { strategy: -1 } },
    ],
  },
  {
    id: 7,
    axis: 'strategy',
    genre: '中二病',
    prompt: '你理想中的殺技是?',
    options: [
      { label: '三段連續面突,絕不給他喘息', score: { strategy: -2 } },
      { label: '出頭小手,你動我就贏', score: { strategy: +2 } },
      { label: '對峙良久看準破綻一招致勝', score: { strategy: -1 } },
    ],
  },
  {
    id: 8,
    axis: 'strategy',
    genre: '人性弱點',
    prompt: '試合前等場邊,你會?',
    options: [
      { label: '原地跳腳、熱身、盯著對手看', score: { strategy: -2 } },
      { label: '盤腿坐著閉目,像睡著了', score: { strategy: +2 } },
      { label: '表面放鬆實則在觀察對手小動作', score: { strategy: +1 } },
    ],
  },
  {
    id: 9,
    axis: 'strategy',
    genre: '道場黑歷史',
    prompt: '隊上有新人第一次上場,你會?',
    options: [
      { label: '教他先發制人,不要被讀牌', score: { strategy: -2 } },
      { label: '教他先穩守,別白給就好', score: { strategy: +2 } },
      { label: '跟他說「看狀況啦」,然後就走了', score: { strategy: +1 } },
    ],
  },
  {
    id: 10,
    axis: 'strategy',
    genre: '現實殘酷',
    prompt: '試合最後 10 秒比分落後 1 本,你會?',
    options: [
      { label: '衝,搏一記面一擊得分反敗', score: { strategy: -2 } },
      { label: '穩住防線,引他冒進然後返打', score: { strategy: +2 } },
      { label: '表面穩實則鎖定他進攻週期找縫', score: { strategy: +1 } },
    ],
  },
  {
    id: 11,
    axis: 'strategy',
    genre: '人性弱點',
    prompt: '跟師範地稽古,你會?',
    options: [
      { label: '反正輸定了,不如拼一記讓他印象深', score: { strategy: -2 } },
      { label: '認真防守,被打也要打得漂亮', score: { strategy: +2 } },
      { label: '觀察他怎麼打你,偷學一點算一點', score: { strategy: +1 } },
    ],
  },
  {
    id: 12,
    axis: 'strategy',
    genre: '中二病',
    prompt: '你理想中的劍道場面是?',
    options: [
      { label: '氣合一喝、飛身壓制、一本決勝負', score: { strategy: -2 } },
      { label: '對手先動,你 0.1 秒後完美反擊', score: { strategy: +2 } },
      { label: '試合最後 0.5 秒雙方同時出手,一本判你', score: { strategy: -1 } },
    ],
  },

  {
    id: 13,
    axis: 'mode',
    genre: '道場黑歷史',
    prompt: '你第一次被師範糾正,印象最深的是?',
    options: [
      { label: '「你的踏み込み落地太散,重來一百次」', score: { mode: -2 } },
      { label: '「你沒有氣,再大聲一點,從丹田!」', score: { mode: +2 } },
      { label: '「動作對但看起來沒殺氣」這種抽象的', score: { mode: -1 } },
    ],
  },
  {
    id: 14,
    axis: 'mode',
    genre: '中二病',
    prompt: '你對「理合」的想像是?',
    options: [
      { label: '每一步節奏、距離、手順都有道理', score: { mode: -2 } },
      { label: '說穿了就是感覺,懂就懂不懂就被打', score: { mode: +2 } },
      { label: '理合是骨架,氣合才是血肉,兩個都要', score: { mode: -1 } },
    ],
  },
  {
    id: 15,
    axis: 'mode',
    genre: '人性弱點',
    prompt: '看影片研究對手,你會注意?',
    options: [
      { label: '起腳時機、重心、進入間合的步伐', score: { mode: -2 } },
      { label: '他什麼時候顯得煩躁、什麼時候鬆懈', score: { mode: +2 } },
      { label: '兩個都看,但記得住的永遠是感覺那塊', score: { mode: +1 } },
    ],
  },
  {
    id: 16,
    axis: 'mode',
    genre: '現實殘酷',
    prompt: '素振 1000 下,你怎麼撐過去?',
    options: [
      { label: '數節拍,每 100 下檢查一次姿勢', score: { mode: -2 } },
      { label: '想像對手,每一劍都當成實戰那一擊', score: { mode: +2 } },
      { label: '開頭數節拍,後面進入神遊狀態', score: { mode: -1 } },
    ],
  },
  {
    id: 17,
    axis: 'mode',
    genre: '中二病',
    prompt: '你最愛的劍道詞彙是?',
    options: [
      { label: '「基本」、「理合」、「打突の機会」', score: { mode: -2 } },
      { label: '「氣合」、「殺気」、「懸待一致」', score: { mode: +2 } },
      { label: '「無心」、「不動智」這種玄學的', score: { mode: +1 } },
    ],
  },
  {
    id: 18,
    axis: 'mode',
    genre: '道場黑歷史',
    prompt: '被打中時,你事後會怎麼檢討?',
    options: [
      { label: '回想他踏進來的那一步,我的手為什麼沒起', score: { mode: -2 } },
      { label: '我被他的氣壓到了,下次氣要比他更強', score: { mode: +2 } },
      { label: '想很久但最後歸因「就是手感不對」', score: { mode: +1 } },
    ],
  },
  {
    id: 19,
    axis: 'mode',
    genre: '人性弱點',
    prompt: '要教新人打第一支面,你會說?',
    options: [
      { label: '先看腳、再看手、最後看重心怎麼移', score: { mode: -2 } },
      { label: '你先大聲喊出來,技術之後再講', score: { mode: +2 } },
      { label: '你先打看看,我看狀況再修', score: { mode: +1 } },
    ],
  },
  {
    id: 20,
    axis: 'mode',
    genre: '現實殘酷',
    prompt: '段審失敗,你覺得是因為?',
    options: [
      { label: '動作細節不夠紮實,日練再練', score: { mode: -2 } },
      { label: '氣勢不到位,評審一眼看穿我心虛', score: { mode: +2 } },
      { label: '可能是運氣,遇到的型不對', score: { mode: +1 } },
    ],
  },
  {
    id: 21,
    axis: 'mode',
    genre: '中二病',
    prompt: '你心中的完美一擊是?',
    options: [
      { label: '踏み込み、手の内、殘心三段到位的教科書面', score: { mode: -2 } },
      { label: '一瞬間整個道場都安靜那種讀秒級的氣場', score: { mode: +2 } },
      { label: '動作很簡單但全場都知道那一擊贏了', score: { mode: -1 } },
    ],
  },
  {
    id: 22,
    axis: 'mode',
    genre: '道場黑歷史',
    prompt: '試合前一晚,你會做什麼?',
    options: [
      { label: '看自己過去錄影,標出哪一步節奏慢', score: { mode: -2 } },
      { label: '看熱血漫畫或電影,把氣勢拉滿', score: { mode: +2 } },
      { label: '正常睡,賽場氣氛會自動催出狀態', score: { mode: +1 } },
    ],
  },
  {
    id: 23,
    axis: 'mode',
    genre: '人性弱點',
    prompt: '你怎麼判斷自己進步了?',
    options: [
      { label: '姿勢影片對比,逐幀看動作變漂亮', score: { mode: -2 } },
      { label: '對練時對手看你的眼神變了', score: { mode: +2 } },
      { label: '贏的場次變多,細節我不想分析', score: { mode: -1 } },
    ],
  },

  {
    id: 24,
    axis: 'mind',
    genre: '中二病',
    prompt: '對手是你的死對頭,你會?',
    options: [
      { label: '冷靜分析他這半年改了什麼', score: { mind: -2 } },
      { label: '深呼吸三次,把恨意變成氣合', score: { mind: +2 } },
      { label: '嘴上說冷靜,內心已經 BGM 放全滿', score: { mind: +1 } },
    ],
  },
  {
    id: 25,
    axis: 'mind',
    genre: '道場黑歷史',
    prompt: '師範當眾批評你,你當下怎麼想?',
    options: [
      { label: '記重點,回家寫下來複習', score: { mind: -2 } },
      { label: '臉熱了一秒,下一個動作要打出來證明', score: { mind: +2 } },
      { label: '表面點頭,內心想反駁但忍住', score: { mind: -1 } },
    ],
  },
  {
    id: 26,
    axis: 'mind',
    genre: '人性弱點',
    prompt: '試合贏了一場,你第一反應是?',
    options: [
      { label: '分析為什麼贏,下一場怎麼延續', score: { mind: -2 } },
      { label: '心臟噗通噗通,想衝過去跟隊友擊拳', score: { mind: +2 } },
      { label: '外表冷靜,但手心已經在出汗', score: { mind: +1 } },
    ],
  },
  {
    id: 27,
    axis: 'mind',
    genre: '現實殘酷',
    prompt: '比分落後,隊友在場邊為你大喊,你會?',
    options: [
      { label: '遮蔽外在聲音,回到自己的戰術節奏', score: { mind: -2 } },
      { label: '聽到那聲就燃起來,整個人進入爆發', score: { mind: +2 } },
      { label: '聽到但不想表現出來,心裡偷偷加油', score: { mind: +1 } },
    ],
  },
  {
    id: 28,
    axis: 'mind',
    genre: '中二病',
    prompt: '打完一個漂亮的一本,你的殘心是?',
    options: [
      { label: '標準姿勢、視線不離對手、回正中', score: { mind: -2 } },
      { label: '一聲氣合配合到位,讓全場都感受到', score: { mind: +2 } },
      { label: '外表標準,心裡在 OS「剛剛那招真帥」', score: { mind: +1 } },
    ],
  },
  {
    id: 29,
    axis: 'mind',
    genre: '道場黑歷史',
    prompt: '稽古最累的時候,撐下去靠?',
    options: [
      { label: '告訴自己「這口氣再撐 20 下」用理智扛', score: { mind: -2 } },
      { label: '喊出來、大吼一聲,用氣合蓋過身體', score: { mind: +2 } },
      { label: '偷看隊友是不是也快死了,彼此互相撐', score: { mind: -1 } },
    ],
  },
  {
    id: 30,
    axis: 'mind',
    genre: '人性弱點',
    prompt: '你羨慕的劍士類型是?',
    options: [
      { label: '動作精準、判斷冷靜、像機器那種', score: { mind: -2 } },
      { label: '氣勢爆棚、一上場就讓對手心理碎', score: { mind: +2 } },
      { label: '看起來溫和,但打出來讓對手無話可說', score: { mind: +1 } },
    ],
  },
  {
    id: 31,
    axis: 'mind',
    genre: '現實殘酷',
    prompt: '連輸三場,教練問你狀態,你回?',
    options: [
      { label: '已經分析出問題在 X,下一場調整', score: { mind: -2 } },
      { label: '我會拼回來,不用擔心', score: { mind: +2 } },
      { label: '沒事,看下一場再說', score: { mind: +1 } },
    ],
  },
  {
    id: 32,
    axis: 'mind',
    genre: '中二病',
    prompt: '你最想擁有的劍士形象是?',
    options: [
      { label: '冷靜、讀秒、像棋手一樣預測所有動作', score: { mind: -2 } },
      { label: '熱血、炸裂、讓對手覺得「這人是魔物」', score: { mind: +2 } },
      { label: '看起來平靜,但一出手就知道不好惹', score: { mind: +1 } },
    ],
  },
  {
    id: 33,
    axis: 'mind',
    genre: '道場黑歷史',
    prompt: '你送給自己的座右銘是?',
    options: [
      { label: '「失敗有原因,勝利不是偶然」', score: { mind: -2 } },
      { label: '「氣不輸,技不輸,魂不輸」', score: { mind: +2 } },
      { label: '「穩住自己,對手自會犯錯」', score: { mind: -1 } },
    ],
  },
  {
    id: 34,
    axis: 'mind',
    genre: '人性弱點',
    prompt: '被打哭的新人,你會怎麼安慰?',
    options: [
      { label: '分析她的動作,告訴她為什麼被打', score: { mind: -2 } },
      { label: '拍她肩膀:「下次打回去就好」', score: { mind: +2 } },
      { label: '安靜陪她走一段,話不多但在', score: { mind: +1 } },
    ],
  },

  {
    id: 35,
    axis: 'style',
    genre: '道場黑歷史',
    prompt: '練習一套新技,你會?',
    options: [
      { label: '分解動作反覆 100 次直到定型才用', score: { style: -2 } },
      { label: '大致會了就在試合用看看,錯了再修', score: { style: +2 } },
      { label: '練到 7 成穩,試合時看情況用', score: { style: -1 } },
    ],
  },
  {
    id: 36,
    axis: 'style',
    genre: '中二病',
    prompt: '你的「得意技」是?',
    options: [
      { label: '只有一招,但練到爐火純青', score: { style: -2 } },
      { label: '手上有五六種,看對手臨場挑', score: { style: +2 } },
      { label: '一招主打,搭配兩三招副技混用', score: { style: -1 } },
    ],
  },
  {
    id: 37,
    axis: 'style',
    genre: '人性弱點',
    prompt: '對手打法跟你一樣,你會?',
    options: [
      { label: '比誰的基本功更紮實,硬碰硬', score: { style: -2 } },
      { label: '故意變招,打他不熟悉的節奏', score: { style: +2 } },
      { label: '開場先照本宣科,中段開始變', score: { style: -1 } },
    ],
  },
  {
    id: 38,
    axis: 'style',
    genre: '現實殘酷',
    prompt: '打到一半,器具出狀況(面紐鬆、竹劍斷),你會?',
    options: [
      { label: '停下,按流程修好再繼續', score: { style: -2 } },
      { label: '簡單處理一下,氣勢不能斷', score: { style: +2 } },
      { label: '看情況,小問題湊合,大問題才停', score: { style: +1 } },
    ],
  },
  {
    id: 39,
    axis: 'style',
    genre: '道場黑歷史',
    prompt: '你對「基本稽古」的感覺是?',
    options: [
      { label: '每天不練會死,沒有捷徑', score: { style: -2 } },
      { label: '偶爾練就好,試合感比較重要', score: { style: +2 } },
      { label: '知道要練,但有時候懶就偷一下', score: { style: +1 } },
    ],
  },
  {
    id: 40,
    axis: 'style',
    genre: '中二病',
    prompt: '你理想的稽古規劃是?',
    options: [
      { label: '每週固定項目,基本 → 技 → 地稽古', score: { style: -2 } },
      { label: '看當天狀態和對象調,不要太死板', score: { style: +2 } },
      { label: '有框架但保留 20% 隨機', score: { style: -1 } },
    ],
  },
  {
    id: 41,
    axis: 'style',
    genre: '人性弱點',
    prompt: '被對手的怪招打中,你的反應是?',
    options: [
      { label: '這不合理合,我回去查是哪個流派', score: { style: -2 } },
      { label: '幹可以這樣,下次我也來試試', score: { style: +2 } },
      { label: '表面平靜,內心已經在抄招', score: { style: +1 } },
    ],
  },
  {
    id: 42,
    axis: 'style',
    genre: '現實殘酷',
    prompt: '試合前一小時,你會?',
    options: [
      { label: '照 checklist 熱身,一分鐘都不差', score: { style: -2 } },
      { label: '看對手誰狀態好,調整待會打法', score: { style: +2 } },
      { label: '大致流程走,但保留心情變化空間', score: { style: -1 } },
    ],
  },
  {
    id: 43,
    axis: 'style',
    genre: '道場黑歷史',
    prompt: '師範講一個新觀念,你的第一反應是?',
    options: [
      { label: '先問「為什麼」,理解了才練', score: { style: -2 } },
      { label: '先照做,練中感覺比想的快', score: { style: +2 } },
      { label: '點頭先,回家再查是不是真的', score: { style: +1 } },
    ],
  },
  {
    id: 44,
    axis: 'style',
    genre: '中二病',
    prompt: '你心中「強」的標準是?',
    options: [
      { label: '百戰如一,每一場都打得像教科書', score: { style: -2 } },
      { label: '每場都不一樣,對手永遠猜不到你', score: { style: +2 } },
      { label: '底子穩,關鍵時刻能變出意料之外', score: { style: +1 } },
    ],
  },
  {
    id: 45,
    axis: 'style',
    genre: '人性弱點',
    prompt: '有人問你「劍道最重要的是什麼?」你會說?',
    options: [
      { label: '基本、反覆、不走捷徑', score: { style: -2 } },
      { label: '應變、讀對手、隨機的勇氣', score: { style: +2 } },
      { label: '紀律為基、靈活為用,兩個缺一不可', score: { style: -1 } },
    ],
  },
]
